version: 2.0
jobs:
  buildBaseImage:
    machine:
      enabled: true
    shell: /bin/bash
    environment:
    working_directory: ~/firemind/base-docker-deploy
    steps:
      - checkout
      - run:
          name: Pull previous image
          command: |
                echo "$FIREMIND_DOCKER_HUB_PASSWORD" | docker login -u "$FIREMIND_DOCKER_HUB_USER" --password-stdin
                docker pull firemindltd/base-install-docker-image-base:latest || true
      - run:
          name: Build Image
          command: |
                docker build -t firemindltd/base-install-docker-image-base:latest ./Base
                docker build -t firemindltd/base-install-docker-image-base:$(git log -1 --pretty=%h | cat) ./Base
      - run:
          name: Push (Dockerhub)
          command: |
                echo "$FIREMIND_DOCKER_HUB_PASSWORD" | docker login -u "$FIREMIND_DOCKER_HUB_USER" --password-stdin
                docker push firemindltd/base-install-docker-image-base:latest
                docker push firemindltd/base-install-docker-image-base:$(git log -1 --pretty=%h | cat)
      - run:
          name: Push (AWS ECR)
          command: |
                aws ecr get-login --region us-east-1 | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com
                docker push firemindltd/base-install-docker-image-base:latest
                docker push firemindltd/base-install-docker-image-base:$(git log -1 --pretty=%h | cat)
              
  buildMainImage:
    machine:
      enabled: true
    shell: /bin/bash
    environment:
    working_directory: ~/firemind/base-docker-deploy
    steps:
      - checkout
      - run:
          name: Pull previous image
          command: |
                echo "$FIREMIND_DOCKER_HUB_PASSWORD" | docker login -u "$FIREMIND_DOCKER_HUB_USER" --password-stdin
                docker pull firemindltd/base-install-docker-image:latest || true
      - run:
          name: Build Main Image
          command: docker build -t firemindltd/base-install-docker-image:latest ./Main
      - run:
          name: Push (Dockerhub)
          command: |
                echo "$FIREMIND_DOCKER_HUB_PASSWORD" | docker login -u "$FIREMIND_DOCKER_HUB_USER" --password-stdin
                docker push firemindltd/base-install-docker-image:latest

  buildNodeJSImage:
    machine:
      enabled: true
    shell: /bin/bash
    environment:
    working_directory: ~/firemind/base-docker-deploy
    steps:
      - checkout
      - run:
          name: Pull previous image
          command: |
                echo "$FIREMIND_DOCKER_HUB_PASSWORD" | docker login -u "$FIREMIND_DOCKER_HUB_USER" --password-stdin
                docker pull firemindltd/base-install-docker-image-nodejs:latest || true
      - run:
          name: Build NodeJS Image
          command: docker build -t firemindltd/base-install-docker-image-nodejs:latest ./Node.JS
      - run:
          name: Push (Dockerhub)
          command: |
                echo "$FIREMIND_DOCKER_HUB_PASSWORD" | docker login -u "$FIREMIND_DOCKER_HUB_USER" --password-stdin
                docker push firemindltd/base-install-docker-image-nodejs:latest

  buildRImage:
    machine:
      enabled: true
    shell: /bin/bash
    environment:
    working_directory: ~/firemind/base-docker-deploy
    steps:
      - checkout
      - run:
          name: Pull previous image
          command: |
                echo "$FIREMIND_DOCKER_HUB_PASSWORD" | docker login -u "$FIREMIND_DOCKER_HUB_USER" --password-stdin
                docker pull firemindltd/base-install-docker-image-r:latest || true
      - run:
          name: Build Image
          command: docker build -t firemindltd/base-install-docker-image-r:latest ./R
      - run:
          name: Push (Dockerhub)
          command: |
                echo "$FIREMIND_DOCKER_HUB_PASSWORD" | docker login -u "$FIREMIND_DOCKER_HUB_USER" --password-stdin
                docker push firemindltd/base-install-docker-image-r:latest

  buildTerraformImage:
    machine:
      enabled: true
    shell: /bin/bash
    environment:
    working_directory: ~/firemind/base-docker-deploy
    steps:
      - checkout
      - run:
          name: Pull previous image
          command: |
                echo "$FIREMIND_DOCKER_HUB_PASSWORD" | docker login -u "$FIREMIND_DOCKER_HUB_USER" --password-stdin
                docker pull firemindltd/base-install-docker-image-terraform:latest || true
      - run:
          name: Build Image
          command: docker build -t firemindltd/base-install-docker-image-terraform:latest ./Terraform
      - run:
          name: Push (Dockerhub)
          command: |
                echo "$FIREMIND_DOCKER_HUB_PASSWORD" | docker login -u "$FIREMIND_DOCKER_HUB_USER" --password-stdin
                docker push firemindltd/base-install-docker-image-terraform:latest

workflows:
  version: 2
  commit:
    jobs:
      - buildBaseImage:
          context:
            - firemind-docker-images
          filters:
            branches:
              only: master
      - buildMainImage:
          context:
            - firemind-docker-images  
          requires:
              - buildBaseImage
      - buildNodeJSImage:
          context:
            - firemind-docker-images  
          requires:
              - buildBaseImage
      - buildRImage:
          context:
            - firemind-docker-images  
          requires:
              - buildBaseImage
      - buildTerraformImage:
          context:
            - firemind-docker-images  
          requires:
              - buildBaseImage
  nightly:
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - buildBaseImage:
          context:
            - firemind-docker-images
      - buildMainImage:
          context:
            - firemind-docker-images
          requires:
            - buildBaseImage
      - buildNodeJSImage:
          context:
            - firemind-docker-images
          requires:
            - buildBaseImage
      - buildRImage:
          context:
            - firemind-docker-images
          requires:
            - buildBaseImage
      - buildTerraformImage:
          context:
            - firemind-docker-images
          requires:
            - buildBaseImage
