version: 2.0
jobs:
  build:
    machine:
      enabled: true
    shell: /bin/bash
    environment:
    working_directory: ~/firemind/base-docker-deploy
    steps:
      - checkout
      - run:
          name: Build Image
          command: docker build -t firemindltd/base-install-docker-image:latest .
      - run:
          name: Build Browser Image
          command: docker build -t firemindltd/base-install-docker-image-browser:latest ./browser
      - run:
          name: Push
          command: |
                echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                docker push firemindltd/base-install-docker-image:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
